routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PeriodController;
use App\Http\Controllers\SallaryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\AllowanceController;
use App\Http\Controllers\EmployeePeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('installed')->group(function () {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false
    ]);

    Route::middleware('auth')->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::match(['get', 'post'], 'edit-profile', [App\Http\Controllers\HomeController::class, 'edit_profile'])->name('edit-profile');

        Route::middleware('admin')->group(function () {
            Route::resource('positions', PositionController::class);
            Route::resource('employees', EmployeeController::class);
            Route::resource('allowances', AllowanceController::class);
            Route::resource('sallaries', SallaryController::class);
            Route::resource('periods', PeriodController::class);
            Route::match(['get', 'post'], 'employee-periods/{employeePeriod}/sallary-panel', [App\Http\Controllers\EmployeePeriodController::class, 'sallaryPanel'])->name('employee-periods.sallary-panel');
            Route::resource('employee-periods', EmployeePeriodController::class);
        });
    });

    Route::get("payroll/{employeePeriod}", [App\Http\Controllers\HomeController::class, 'payroll'])->name('payroll');
});

Route::middleware('installation')->group(function () {
    Route::match(['get', 'post'], 'installation', [App\Http\Controllers\HomeController::class, 'installation'])->name('installation');
});

app/Models/Allowance.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Allowance
 *
 * @property $id
 * @property $position_id
 * @property $name
 * @property $amount
 * @property $allowance_type
 * @property $created_at
 * @property $updated_at
 *
 * @property Position $position
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Allowance extends Model
{
    
    static $rules = [
		'position_id' => 'required',
		'name' => 'required',
		'amount' => 'required',
		'allowance_type' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['position_id','name','amount','allowance_type'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function position()
    {
        return $this->hasOne('App\Models\Position', 'id', 'position_id');
    }

    public function getAmountFormatAttribute()
    {
      $amount = number_format($this->amount);
      return $this->allowance_type == 'Fixed' ? 'Rp. '.$amount : $amount.' %';
    }
    

}

app/Http/Controllers/AllowanceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Position;
use App\Models\Allowance;
use Illuminate\Http\Request;

/**
 * Class AllowanceController
 * @package App\Http\Controllers
 */
class AllowanceController extends Controller
{

    function __construct()
    {
        $this->position = new Position;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allowances = Allowance::paginate();

        return view('allowance.index', compact('allowances'))
            ->with('i', (request()->input('page', 1) - 1) * $allowances->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $allowance = new Allowance();
        $positions = $this->position->get()->pluck('name','id');
        return view('allowance.create', compact('allowance','positions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate(Allowance::$rules);

        $allowance = Allowance::create($request->all());

        return redirect()->route('allowances.index')
            ->with('success', 'Allowance created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $allowance = Allowance::find($id);

        return view('allowance.show', compact('allowance'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $allowance = Allowance::find($id);
        $positions = $this->position->get()->pluck('name','id');

        return view('allowance.edit', compact('allowance','positions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Allowance $allowance
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Allowance $allowance)
    {
        request()->validate(Allowance::$rules);

        $allowance->update($request->all());

        return redirect()->route('allowances.index')
            ->with('success', 'Allowance updated successfully');
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $allowance = Allowance::find($id)->delete();

        return redirect()->route('allowances.index')
            ->with('success', 'Allowance deleted successfully');
    }
}

resources/views/allowance/create.blade.php
@extends('layouts.app')

@section('template_title')
    Buat Tunjangan
@endsection

@section('content')
    <section class="content container">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Buat Tunjangan</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('allowances.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('allowance.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/allowance/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Tunjangan
@endsection

@section('content')
    <section class="content container">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Tunjangan</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('allowances.update', $allowance->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('allowance.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/allowance/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('jabatan') }}
            {{ Form::select('position_id', $positions, $allowance->position_id, ['class' => 'form-control' . ($errors->has('position_id') ? ' is-invalid' : ''), 'placeholder' => '- Pilih Jabatan -']) }}
            {!! $errors->first('position_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('nama') }}
            {{ Form::text('name', $allowance->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => 'Nama']) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('jumlah') }}
            {{ Form::number('amount', $allowance->amount, ['class' => 'form-control' . ($errors->has('amount') ? ' is-invalid' : ''), 'placeholder' => 'Jumlah']) }}
            {!! $errors->first('amount', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('tipe') }}
            {{ Form::select('allowance_type', ['Percent'=>'Percent','Fixed'=>'Fixed'], $allowance->allowance_type, ['class' => 'form-control' . ($errors->has('allowance_type') ? ' is-invalid' : ''), 'placeholder' => '- Pilih Tipe -']) }}
            {!! $errors->first('allowance_type', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/allowance/index.blade.php
@extends('layouts.app')

@section('template_title')
    Tunjangan Jabatan
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Tunjangan Jabatan') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('allowances.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Buat Baru') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $message }}
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>Jabatan</th>
										<th>Nama</th>
										<th>Jumlah</th>
										<th>Tipe</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($allowances as $allowance)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $allowance->position->name }}</td>
											<td>{{ $allowance->name }}</td>
											<td>{{ $allowance->amount_format }}</td>
											<td>{{ $allowance->allowance_type }}</td>

                                            <td>
                                                <form action="{{ route('allowances.destroy',$allowance->id) }}" method="POST" onsubmit="if(confirm('Apakah anda yakin menghapus data ini ?')){return true}else{return false}">
                                                    <a class="btn btn-sm btn-success" href="{{ route('allowances.edit',$allowance->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $allowances->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/allowance/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $allowance->name ?? 'Show Allowance' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Show Allowance</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('allowances.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Position Id:</strong>
                            {{ $allowance->position_id }}
                        </div>
                        <div class="form-group">
                            <strong>Name:</strong>
                            {{ $allowance->name }}
                        </div>
                        <div class="form-group">
                            <strong>Amount:</strong>
                            {{ $allowance->amount }}
                        </div>
                        <div class="form-group">
                            <strong>Allowance Type:</strong>
                            {{ $allowance->allowance_type }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection