routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PeriodController;
use App\Http\Controllers\SallaryController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use App\Http\Controllers\AllowanceController;
use App\Http\Controllers\EmployeePeriodController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('installed')->group(function () {
    Auth::routes([
        'register' => false,
        'reset' => false,
        'verify' => false
    ]);

    Route::middleware('auth')->group(function () {
        Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
        Route::match(['get', 'post'], 'edit-profile', [App\Http\Controllers\HomeController::class, 'edit_profile'])->name('edit-profile');

        Route::middleware('admin')->group(function () {
            Route::resource('positions', PositionController::class);
            Route::resource('employees', EmployeeController::class);
            Route::resource('allowances', AllowanceController::class);
            Route::resource('sallaries', SallaryController::class);
            Route::resource('periods', PeriodController::class);
            Route::match(['get', 'post'], 'employee-periods/{employeePeriod}/sallary-panel', [App\Http\Controllers\EmployeePeriodController::class, 'sallaryPanel'])->name('employee-periods.sallary-panel');
            Route::resource('employee-periods', EmployeePeriodController::class);
        });
    });

    Route::get("payroll/{employeePeriod}", [App\Http\Controllers\HomeController::class, 'payroll'])->name('payroll');
});

Route::middleware('installation')->group(function () {
    Route::match(['get', 'post'], 'installation', [App\Http\Controllers\HomeController::class, 'installation'])->name('installation');
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class Employee
 *
 * @property $id
 * @property $user_id
 * @property $position_id
 * @property $NIK
 * @property $NPWP
 * @property $name
 * @property $work_around
 * @property $bank_account
 * @property $created_at
 * @property $updated_at
 *
 * @property EmployeePeriod[] $employeePeriods
 * @property EmployeeSallary[] $employeeSallaries
 * @property Position $position
 * @property User $user
 * @package App
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Employee extends Model
{

    static $rules = [
        'position_id' => 'required',
        'NIK' => 'required|unique:employees',
        'name' => 'required',
        'work_around' => 'required',
    ];

    protected $perPage = 20;

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['user_id', 'position_id', 'NIK', 'NPWP', 'name', 'work_around', 'bank_account'];


    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function employeePeriods()
    {
        return $this->hasMany('App\Models\EmployeePeriod', 'employee_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function employeeSallaries()
    {
        return $this->hasMany('App\Models\EmployeeSallary', 'employee_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function position()
    {
        return $this->hasOne('App\Models\Position', 'id', 'position_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'user_id');
    }

    function getGajiPokokAttribute()
    {
        return $this->position->sallary;
    }

    function getBiayaJabatanAttribute()
    {
        return $this->position->cost;
    }

    function getTunjanganAttribute()
    {
        $ref_tunjangan = $this->position->allowances;
        $tunjangan = 0;
        foreach ($ref_tunjangan as $t) {
            if ($t->allowance_type == 'Percent')
                $tunjangan += $this->gaji_pokok * $t->amount / 100;
            else
                $tunjangan += $t->amount;
        }

        return $tunjangan;
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\Employee;
use App\Models\Position;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

/**
 * Class EmployeeController
 * @package App\Http\Controllers
 */
class EmployeeController extends Controller
{
    function __construct()
    {
        $this->position = new Position;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::paginate();

        return view('employee.index', compact('employees'))
            ->with('i', (request()->input('page', 1) - 1) * $employees->perPage());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $employee = new Employee();
        $positions = $this->position->get()->pluck('name','id');
        return view('employee.create', compact('employee','positions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = Employee::$rules;
        $rules['password'] = 'required';
        request()->validate($rules);

        DB::beginTransaction();
        try {
            //code...
            $user = User::create([
                'name' => $request->name,
                'email' => $request->NIK,
                'password' => $request->password,
            ]);
            $data = $request->all();
            $data['user_id'] = $user->id;
            $employee = Employee::create($data);
            DB::commit();
            return redirect()->route('employees.index')
            ->with('success', 'Berhasil buat karyawan.');
        } catch (\Throwable $th) {
            // throw $th;
            DB::rollback();
            return redirect()->back()->withInput();
        }

        return;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);

        return view('employee.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::find($id);
        $positions = $this->position->get()->pluck('name','id');

        return view('employee.edit', compact('employee','positions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  Employee $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $rules = Employee::$rules;
        $rules['NIK'] = $rules['NIK'] . ',id,' . $employee->id;
        request()->validate($rules);
        DB::beginTransaction();
        try {
            //code...
            if($request->password)
                $employee->user->update(['password'=>$request->password]);

            $employee->user->update([
                'name' => $request->name,
                'email' => $request->NIK
            ]);

            $employee->update($request->all());
            DB::commit();
            return redirect()->route('employees.index')
            ->with('success', 'Berhasil update karyawan.');
        } catch (\Throwable $th) {
            // throw $th;
            DB::rollback();
            return redirect()->back()->withInput();
        }
    }

    /**
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        Employee::find($id)->user->delete();

        return redirect()->route('employees.index')
            ->with('success', 'Employee deleted successfully');
    }
}

resources/views/employee/create.blade.php
@extends('layouts.app')

@section('template_title')
    Karywan Baru
@endsection

@section('content')
    <section class="content container">
        <div class="row">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Karywan Baru</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('employees.store') }}"  role="form" enctype="multipart/form-data">
                            @csrf

                            @include('employee.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/employee/edit.blade.php
@extends('layouts.app')

@section('template_title')
    Update Employee
@endsection

@section('content')
    <section class="content container">
        <div class="">
            <div class="col-md-12">

                @includeif('partials.errors')

                <div class="card card-default">
                    <div class="card-header">
                        <span class="card-title">Update Employee</span>
                    </div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('employees.update', $employee->id) }}"  role="form" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            @csrf

                            @include('employee.form')

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/employee/form.blade.php
<div class="box box-info padding-1">
    <div class="box-body">
        
        <div class="form-group">
            {{ Form::label('jabatan') }}
            {{ Form::select('position_id', $positions, $employee->position_id, ['class' => 'form-control' . ($errors->has('position_id') ? ' is-invalid' : ''), 'placeholder' => '- Pilih Jabatan -']) }}
            {!! $errors->first('position_id', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('NIK') }}
            {{ Form::number('NIK', $employee->NIK, ['class' => 'form-control' . ($errors->has('NIK') ? ' is-invalid' : ''), 'placeholder' => 'NIK']) }}
            {!! $errors->first('NIK', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('NPWP') }}
            {{ Form::number('NPWP', $employee->NPWP, ['class' => 'form-control' . ($errors->has('NPWP') ? ' is-invalid' : ''), 'placeholder' => 'NPWP']) }}
            {!! $errors->first('NPWP', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('nama') }}
            {{ Form::text('name', $employee->name, ['class' => 'form-control' . ($errors->has('name') ? ' is-invalid' : ''), 'placeholder' => 'Nama']) }}
            {!! $errors->first('name', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('area_kerja') }}
            {{ Form::text('work_around', $employee->work_around, ['class' => 'form-control' . ($errors->has('work_around') ? ' is-invalid' : ''), 'placeholder' => 'Area Kerja']) }}
            {!! $errors->first('work_around', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('No. Rekening') }}
            {{ Form::text('bank_account', $employee->bank_account, ['class' => 'form-control' . ($errors->has('bank_account') ? ' is-invalid' : ''), 'placeholder' => 'No. Rekening']) }}
            {!! $errors->first('bank_account', '<div class="invalid-feedback">:message</p>') !!}
        </div>
        <div class="form-group">
            {{ Form::label('Password') }}
            <input type="password" name="password" id="" class="form-control {{$errors->has('password') ? ' is-invalid' : ''}}" placeholder="Password">
            {!! $errors->first('password', '<div class="invalid-feedback">:message</p>') !!}
        </div>

    </div>
    <div class="box-footer mt20">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('template_title')
    Karyawan
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <div style="display: flex; justify-content: space-between; align-items: center;">

                            <span id="card_title">
                                {{ __('Karyawan') }}
                            </span>

                             <div class="float-right">
                                <a href="{{ route('employees.create') }}" class="btn btn-primary btn-sm float-right"  data-placement="left">
                                  {{ __('Buat Karyawan Baru') }}
                                </a>
                              </div>
                        </div>
                    </div>
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            {{ $message }}
                        </div>
                    @endif

                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover">
                                <thead class="thead">
                                    <tr>
                                        <th>No</th>
                                        
										<th>NIK</th>
										<th>Nama</th>
										<th>Username</th>
										<th>Jabatan</th>
										<th>Area Kerja</th>
										<th>No. Rekening</th>

                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($employees as $employee)
                                        <tr>
                                            <td>{{ ++$i }}</td>
                                            
											<td>{{ $employee->NIK }}</td>
											<td>{{ $employee->name }}</td>
											<td>{{ $employee->user->email }}</td>
											<td>{{ $employee->position->name }}</td>
											<td>{{ $employee->work_around }}</td>
											<td>{{ $employee->bank_account }}</td>

                                            <td>
                                                <form action="{{ route('employees.destroy',$employee->id) }}" method="POST" onsubmit="if(confirm('Apakah anda yakin menghapus data ini ?')){return true}else{return false}">
                                                    <a class="btn btn-sm btn-success" href="{{ route('employees.edit',$employee->id) }}"><i class="fa fa-fw fa-edit"></i> Edit</a>
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-fw fa-trash"></i> Hapus</button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {!! $employees->links() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/employee/show.blade.php
@extends('layouts.app')

@section('template_title')
    {{ $employee->name ?? 'Tampil Karyawan' }}
@endsection

@section('content')
    <section class="content container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="float-left">
                            <span class="card-title">Tampil Karyawan</span>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary" href="{{ route('employees.index') }}"> Back</a>
                        </div>
                    </div>

                    <div class="card-body">
                        
                        <div class="form-group">
                            <strong>Jabatan:</strong>
                            {{ $employee->position->name }}
                        </div>
                        <div class="form-group">
                            <strong>NIK:</strong>
                            {{ $employee->NIK }}
                        </div>
                        <div class="form-group">
                            <strong>NPWP:</strong>
                            {{ $employee->NPWP }}
                        </div>
                        <div class="form-group">
                            <strong>Nama:</strong>
                            {{ $employee->name }}
                        </div>
                        <div class="form-group">
                            <strong>Area Kerja:</strong>
                            {{ $employee->work_around }}
                        </div>
                        <div class="form-group">
                            <strong>No. Rekening:</strong>
                            {{ $employee->bank_account }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection